import type { SoundCue } from './session'

// Two tiny, locally embedded PCM WAV assets keep feedback deterministic and offline.
const WAV: Record<SoundCue['type'], string> = {
  LEVEL_REACHED: 'UklGRsQFAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YaAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9CGKKvQn3hq5BtDw5N6s1ZLXGOTz9+sNOyATKt4o6xxgCV7zreA41r3WGeJQ9VcLYh5yKZ4p2x79C/j1luLu1hHWOOC58rcIahynKDUqrCCODp34nOTO14/Vd94v8A4GVhqzJ6EqXSIREUn7vubX2DnV2Ny07V8DJxiWJuIq6iOCE/r9+ugH2g3VXdtN660A3xVTJfgqUyXfFa0ATetd2w3VB9r66Pr9ghPqI+IqliYnGF8DtO3Y3DnV19i+5kn7ERFdIqEqsydWGg4GL/B33o/Vztec5J34jg6sIDUqpyhqHLcIufI44BHW7taW4vj1/QvbHp4pciliHlcLUPUZ4r3WONat4F7zYAnrHN4oEyo7IOsN8/cY5JLXrNXk3tDwuQbeGvQniir0IXIQnfoz5pHYStU93VHuCwS1GOEm1iqKI+cSTf1p6LfZFNW42+XrWgFzFqcl9yr8JEoVAAC26gTbCdVZ2o3ppv4bFEgk7CpJJpcXswIZ7XbcKtUf2Uvn9fuvEcMitipvJ80ZYwWO7wzedtUM2CLlR/kwDxwhVCpuKOgbDQgV8sXf7dUi1xXjoPaiDFMfyClDKecdsAqp9J7hjtZi1iXhA/QICmodEinvKcgfRw1J95bjWdfL1VTfcvFjB2QbMihxKokh0Q/y+arlTdhf1aPd7+63BEIZKSfHKigjTBKh/Nnnatke1RbcfuwGAgYX+SXzKqMksxRT/yHqrdoI1a3aIepT/7MUoyTzKvklBhcGAn7sFtwe1WrZ2eeh/EwSKCPHKiknQhm3BO/uo91f1U3YquXy+dEPiSFxKjIoZBtjB3LxVN/L1VnXluNJ90cNyB/vKRIpah0ICgP0JeFi1o7WnuGp9LAK5x1DKcgpUx+iDKD2FeMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
  BOOSTER_ACTIVATED: 'UklGRsQFAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YaAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEyoZJGAJQ+k41jDbUPWVFXIpfSX9C5nr7tbe2bnyNROnKLwmjg4D7s7Xs9gv8MEQsyfTJxERf/DX2LDXtO09DpYmwyiCEwvzB9rV1k3rqgtTJYkp3xWk9V3bJNb66AsJ6iMlKicYSPjY3J3VvuZjBl0ilipWGvP6d95B1ZzktQOsIN0qahyk/TjgENWW4gMB2x74KmIeVgAZ4gvVreBQ/usc5yo7IAkDGOQx1eTen/veGqwq9CG4BTPmgtU93fL4tRhFKoojYghp6P7VuNtM9nMWtCn8JAMLtuql1lnasPMbFPgoSSaZDRntddcf2SHxrxETKG8nIhCO72/YDNig7jAPBiduKJoSFfKQ2SLXMeyiDNElQyn/FKn02Npi1tbpCAp2JO8pTxdJ90bcy9WS52MH9iJxKocZ8vnY3V/VZuW3BFIhxyqmG6H8jN8e1VXjBgKOH/MqqR1T/2HhCNVh4VP/qR3zKo4fBgJV4x7VjN+h/KYbxypSIbcEZuVf1djd8vmHGXEq9iJjB5Lny9VG3En3TxfvKXYkCArW6WLW2Nqp9P8UQynRJaIMMewi15DZFfKaEm4oBicwD6DuDNhv2I7vIhBvJxMorxEh8R/ZddcZ7ZkNSSb4KBsUsPNZ2qXWtuoDC/wktClzFkz2uNv+1WnoYgiKI0UqtRjy+D3dgtUz5rgF9CGsKt4an/vk3jHVGOQJAzsg5yrrHFD+reAL1RniVgBiHvgq2x4DAZbiENU44KT9ahzdKqwgtQOc5EHVd97z+lYalipdImMGvuad1djcSPgnGCUq6iMLCfroJNZd26T13xWJKVMlqgtN69XWB9oL84ITwyiWJj0OtO2w19fYf/AREdMnsyfBEC/ws9jO1wPujg68JqcoNRMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
}

type AudioContextConstructor = new () => AudioContext

export class GameAudio {
  private context?: AudioContext
  private buffers = new Map<SoundCue['type'], AudioBuffer>()
  private loading?: Promise<void>
  private muted = false

  setMuted(value: boolean) { this.muted = value }

  unlock = () => {
    if (typeof window === 'undefined') return
    const AudioContextClass = window.AudioContext ?? (window as Window & { webkitAudioContext?: AudioContextConstructor }).webkitAudioContext
    if (!AudioContextClass) return
    this.context ??= new AudioContextClass()
    if (this.context.state === 'suspended') void this.context.resume().catch(() => {})
    this.loading ??= Promise.all(Object.entries(WAV).map(async ([type, base64]) => {
      const bytes = Uint8Array.from(atob(base64), char => char.charCodeAt(0))
      const buffer = await this.context!.decodeAudioData(bytes.buffer)
      this.buffers.set(type as SoundCue['type'], buffer)
    })).then(() => {}).catch(() => {})
  }

  play = (cue: SoundCue) => {
    const context = this.context
    const buffer = this.buffers.get(cue.type)
    if (this.muted || !context || context.state !== 'running' || !buffer) return
    const source = context.createBufferSource()
    const gain = context.createGain()
    source.buffer = buffer
    gain.gain.value = cue.type === 'BOOSTER_ACTIVATED' ? 0.24 : 0.18
    source.connect(gain); gain.connect(context.destination)
    source.addEventListener('ended', () => { source.disconnect(); gain.disconnect() }, { once: true })
    source.start()
  }
}

export const gameAudio = new GameAudio()
