import type { Catalog, Round, Theme } from '../api/types'
import { multiplier, number } from '../game/format'
import { Balloon } from './App'

export function Setup({ theme, onTheme, catalog, stake, onStake, booster, onBooster, balance, busy, onStart, onRules, onHistory }: { theme: Theme; onTheme: (t: Theme) => void; catalog: Catalog; stake: number; onStake: (n: number) => void; booster: number; onBooster: (n: number) => void; balance: number; busy: boolean; onStart: () => void; onRules: () => void; onHistory: () => void }) {
  const scale = 10 ** catalog.stakeRules.decimalPlaces
  const invalidStake = stake < catalog.stakeRules.minimum || stake > catalog.stakeRules.maximum || Math.round(stake * scale) !== stake * scale
  const insufficient = stake > balance
  return <><div className="theme-picker" role="group" aria-label="Тема полёта">{(['GREEN', 'RED'] as Theme[]).map(t => <button key={t} className={`theme-card ${t.toLowerCase()} ${theme === t ? 'selected' : ''}`} aria-pressed={theme === t} disabled={busy} onClick={() => onTheme(t)}><span className="theme-icon" aria-hidden="true">{t === 'GREEN' ? '↗' : '↟'}</span><span><strong>{t === 'GREEN' ? 'Green Balloon' : 'Red Balloon'}</strong><small>{catalog.levels[t]} уровней · {t === 'GREEN' ? 'Классический маршрут' : 'Больше высоты'}</small></span><span className="selection-dot" aria-hidden="true">{theme === t ? '✓' : ''}</span></button>)}</div>
    <section className="setup-card"><div className="sky-preview"><span className="sky-label">{theme} / {catalog.levels[theme]} УРОВНЕЙ</span><div className="sun-disc" /><div className="preview-balloon"><Balloon /></div><div className="cloud-shape cloud-a" /><div className="cloud-shape cloud-b" /><div className="hill hill-back" /><div className="hill hill-front" /><div className="preview-copy"><h2>Небо зовёт.</h2><p>Вы выбираете высоту.<br />И момент, когда остановиться.</p></div><div className="preview-levels" aria-label={`${catalog.levels[theme]} уровней`}>{Array.from({ length: catalog.levels[theme] }, (_, i) => <span key={i} data-testid="preview-level">{String(i + 1).padStart(2, '0')}</span>)}</div></div>
    <div className="bet-form"><div className="field-heading"><h3>01 <span>Ставка + бустер</span></h3><span>ровно 4 варианта</span></div><div className="option-grid paired-options" role="radiogroup" aria-label="Вариант ставки и бустера">{catalog.boosters.map((boost, index) => { const amount = catalog.stakes[index]; const selected = stake === amount && booster === boost; return <button data-testid="flight-option" data-stake={amount} data-booster={boost} role="radio" aria-checked={selected} key={boost} disabled={busy || amount > balance} title={amount > balance ? 'Недостаточно бонусов' : undefined} onClick={() => { onStake(amount); onBooster(boost) }}><strong>{number(amount)}</strong><span>{boost === 1 ? '×1 · без усиления' : `×${boost} · позиция видна сразу`}</span></button> })}</div>
      {invalidStake ? <p role="status" className="error">Ставка должна быть от {number(catalog.stakeRules.minimum)} до {number(catalog.stakeRules.maximum)}.</p> : insufficient ? <p role="status" className="error">Недостаточно бонусов: для ставки нужно {number(stake)}, доступно {number(balance)}.</p> : <p className="field-hint">Спишем {number(stake)} бонусов при старте.</p>}
      <p className="field-hint">{booster === 1 ? 'Спокойный старт без усиления.' : `×${booster} к коэффициенту на отмеченном уровне — до cashout.`}</p>
      <div className="bet-summary"><span>Стоимость полёта</span><strong>{number(stake)} <small>бонусов</small></strong></div><button className="primary start-button" disabled={busy || insufficient || invalidStake} onClick={onStart}>{busy ? 'Готовим полёт…' : 'Начать полёт'} <span aria-hidden="true">↗</span></button><div className="bet-links"><button onClick={onRules}>Как играть?</button><button onClick={onHistory}>История полётов ↗</button></div>
    </div></section></>
}

export function Flight({ round: r, connection, busy, notice, showCashoutHint = false, onCashout, onFairness, onReconnect }: { round: Round; connection: string; busy: boolean; notice: string; showCashoutHint?: boolean; onCashout: () => void; onFairness: () => void; onReconnect: () => void }) {
  const crashed = r.status === 'CRASHED' || r.status === 'FINISHED'
  return <section className={`flight-card ${crashed ? 'has-crashed' : ''} ${r.boosterActivated ? 'has-booster' : ''}`} data-testid="active-round">
    <div className="flight-top"><span className="pill">{r.theme} · {r.totalLevels} уровней · <b data-testid="round-id">{r.id}</b></span><span data-testid="connection-state" className={`connection ${connection === 'connected' ? 'online' : ''}`}>{connection === 'connected' ? '● На связи' : connection === 'recovering' ? '◌ Восстанавливаем…' : '○ Нет связи'}</span></div>
    {connection !== 'connected' && <div className="connection-alert" role="status">Полёт продолжается на стороне источника данных. Ждём актуальный snapshot. <button onClick={onReconnect}>Восстановить</button></div>}
    <div className="flight-stage"><div className="flight-multiplier"><span>{crashed ? 'ПОЛЁТ ЗАВЕРШЁН' : r.cashoutPerformed ? 'ПОЛЁТ ПРОДОЛЖАЕТСЯ' : 'ТЕКУЩИЙ КОЭФФИЦИЕНТ'}</span><strong data-testid="multiplier">{multiplier(crashed ? r.crashMultiplier! : r.currentMultiplier)}</strong><small data-testid="current-level">{crashed ? 'Шар лопнул' : `Уровень ${r.currentLevel} из ${r.totalLevels}`}</small><i data-testid="event-sequence">{r.sequence}</i></div><div className="altitude-lines" aria-hidden="true">{[1, 2, 3, 4].map(i => <i key={i} />)}</div><div className="sun-disc" /><div className="cloud-shape cloud-a" /><div className="cloud-shape cloud-b" />
      <div className="flying-balloon" style={{ bottom: `${15 + r.currentLevel / r.totalLevels * 45}%` }}><Balloon /><span className="burst" aria-hidden="true">✷</span></div>
      <div className="flight-levels" aria-label="Прогресс по уровням">{r.levelThresholds.map((threshold, i) => { const boosterHere = r.boosterMultiplier > 1 && r.boosterLevel === i + 1; const boosterState = r.boosterActivated ? 'активирован' : r.cashoutPerformed ? 'не сработает' : 'ожидает'; return <div key={i} data-testid="flight-level" className={`${i < r.currentLevel ? 'passed' : ''} ${boosterHere ? 'booster-level' : ''}`} aria-label={`Уровень ${i + 1}: ${i < r.currentLevel ? 'пройден' : 'впереди'}${boosterHere ? `, бустер ×${r.boosterMultiplier} ${boosterState}` : ''}`}><span>{String(i + 1).padStart(2, '0')}</span><i /><small>{multiplier(threshold)}</small>{boosterHere && <b data-testid="booster-marker" title={`Бустер ×${r.boosterMultiplier} · уровень ${i + 1}`}>×{r.boosterMultiplier}</b>}</div> })}</div>
      <div className="level-toast" key={notice} role="status">{notice || 'Первый уровень откроет cashout'}</div>
    </div>
    <div className="flight-dashboard"><div className="flight-stats"><div><span>Ставка</span><strong>{number(r.betAmount)}</strong></div><div><span>Бустер</span><strong data-testid="booster-state">{r.boosterMultiplier === 1 ? '×1' : `×${r.boosterMultiplier}`} {r.boosterMultiplier > 1 && <small>{r.boosterActivated ? 'активирован' : r.cashoutPerformed ? 'не сработает' : 'позиция открыта'}</small>}</strong></div><div><span>Игровые очки</span><strong data-testid="round-points">{number(r.roundScore)} ✧</strong></div></div>
      {r.cashoutPerformed ? <div className="cashout-fixed" role="status"><strong>Зафиксировано {number(r.winAmount)} бонусов · {multiplier(r.cashoutMultiplier!)}</strong><small>Выплата сохранена. Шар продолжает полёт до падения.</small></div> : <div className="cashout-action">{showCashoutHint && <div className="cashout-onboarding" role="status" aria-live="polite">Забрать выигрыш можно после первого уровня</div>}<button className="primary cashout-button" onClick={onCashout} disabled={!r.cashoutAvailable || busy || crashed || connection !== 'connected'}>{crashed ? 'Полёт завершён' : busy ? 'Фиксируем…' : <><span>Забрать {r.cashoutPreviewAmount === undefined ? '—' : `${number(r.cashoutPreviewAmount)} бонусов`}</span><small>{multiplier(r.currentMultiplier)}</small></>} <i aria-hidden="true">↙</i></button><small>{crashed ? 'Готовим результат…' : r.cashoutAvailable ? 'Сумма подтверждена сервером' : 'Доступно после первого уровня'}</small></div>}
    </div><button className="fairness-link" onClick={onFairness}>◇ Проверить честность</button>
  </section>
}
