import type { Catalog, Round, Theme } from '../api/types'
import { Balloon } from './App'
import { multiplier, number } from './Panels'

export function Setup({ theme, onTheme, catalog, stake, onStake, booster, onBooster, balance, busy, onStart, onRules, onHistory }: { theme: Theme; onTheme: (t: Theme) => void; catalog: Catalog; stake: number; onStake: (n: number) => void; booster: number; onBooster: (n: number) => void; balance: number; busy: boolean; onStart: () => void; onRules: () => void; onHistory: () => void }) {
  const insufficient = stake > balance
  return <><div className="theme-picker" role="group" aria-label="Тема полёта">{(['GREEN', 'RED'] as Theme[]).map(t => <button key={t} className={`theme-card ${t.toLowerCase()} ${theme === t ? 'selected' : ''}`} aria-pressed={theme === t} disabled={busy} onClick={() => onTheme(t)}><span className="theme-icon" aria-hidden="true">{t === 'GREEN' ? '↗' : '↟'}</span><span><strong>{t === 'GREEN' ? 'Green Balloon' : 'Red Balloon'}</strong><small>{catalog.thresholds[t].length} уровней · {t === 'GREEN' ? 'Классический маршрут' : 'Больше высоты'}</small></span><span className="selection-dot" aria-hidden="true">{theme === t ? '✓' : ''}</span></button>)}</div>
    <section className="setup-card"><div className="sky-preview"><span className="sky-label">{theme} / {catalog.thresholds[theme].length} УРОВНЕЙ</span><div className="sun-disc" /><div className="preview-balloon"><Balloon /></div><div className="cloud-shape cloud-a" /><div className="cloud-shape cloud-b" /><div className="hill hill-back" /><div className="hill hill-front" /><div className="preview-copy"><h2>Небо зовёт.</h2><p>Вы выбираете высоту.<br />И момент, когда остановиться.</p></div><div className="preview-levels" aria-label={`${catalog.thresholds[theme].length} уровней`}>{catalog.thresholds[theme].map((_, i) => <span key={i} data-testid="preview-level">{String(i + 1).padStart(2, '0')}</span>)}</div></div>
    <div className="bet-form"><div className="field-heading"><h3>01 <span>Ваша ставка</span></h3><span>бонусы</span></div><div className="option-grid" role="group" aria-label="Ставка">{catalog.stakes.map(n => <button key={n} aria-pressed={stake === n} disabled={busy || n > balance} title={n > balance ? 'Недостаточно бонусов' : undefined} onClick={() => onStake(n)}>{number(n)}</button>)}</div>
      {insufficient ? <p role="status" className="error">Недостаточно бонусов: для ставки нужно {number(stake)}, доступно {number(balance)}.</p> : <p className="field-hint">Спишем {number(stake)} бонусов при старте.</p>}
      <div className="field-heading"><h3>02 <span>Усиление полёта</span></h3><span>бустер</span></div><div className="option-grid boosters" role="group" aria-label="Бустер">{catalog.boosters.map(n => <button key={n} aria-pressed={booster === n} disabled={busy} onClick={() => onBooster(n)}>{n === 1 ? 'Без бустера' : `×${n}`}</button>)}</div><p className="field-hint">{booster === 1 ? 'Спокойный старт без усиления.' : `×${booster} к коэффициенту на одном из скрытых уровней — до cashout.`}</p>
      <div className="bet-summary"><span>Стоимость полёта</span><strong>{number(stake)} <small>бонусов</small></strong></div><button className="primary start-button" disabled={busy || insufficient} onClick={onStart}>{busy ? 'Готовим полёт…' : 'Начать полёт'} <span aria-hidden="true">↗</span></button><div className="bet-links"><button onClick={onRules}>Как играть?</button><button onClick={onHistory}>История полётов ↗</button></div>
    </div></section></>
}

export function Flight({ round: r, connection, busy, notice, onCashout, onFairness, onReconnect }: { round: Round; connection: string; busy: boolean; notice: string; onCashout: () => void; onFairness: () => void; onReconnect: () => void }) {
  const crashed = r.status === 'CRASHED' || r.status === 'FINISHED'
  return <section className={`flight-card ${crashed ? 'has-crashed' : ''} ${r.boosterActivated ? 'has-booster' : ''}`}>
    <div className="flight-top"><span className="pill">{r.theme} · {r.totalLevels} уровней</span><span className={`connection ${connection === 'connected' ? 'online' : ''}`}>{connection === 'connected' ? '● На связи' : connection === 'recovering' ? '◌ Восстанавливаем…' : '○ Нет связи'}</span></div>
    {connection !== 'connected' && <div className="connection-alert" role="status">Полёт продолжается на стороне источника данных. Ждём актуальный snapshot. <button onClick={onReconnect}>Восстановить</button></div>}
    <div className="flight-stage"><div className="flight-multiplier"><span>{crashed ? 'ПОЛЁТ ЗАВЕРШЁН' : r.cashoutPerformed ? 'ПОЛЁТ ПРОДОЛЖАЕТСЯ' : 'ТЕКУЩИЙ КОЭФФИЦИЕНТ'}</span><strong data-testid="multiplier">{multiplier(crashed ? r.crashMultiplier! : r.currentMultiplier)}</strong><small>{crashed ? 'Шар лопнул' : `Уровень ${r.currentLevel} из ${r.totalLevels}`}</small></div><div className="altitude-lines" aria-hidden="true">{[1, 2, 3, 4].map(i => <i key={i} />)}</div><div className="sun-disc" /><div className="cloud-shape cloud-a" /><div className="cloud-shape cloud-b" />
      <div className="flying-balloon" style={{ bottom: `${15 + r.currentLevel / r.totalLevels * 45}%` }}><Balloon /><span className="burst" aria-hidden="true">✷</span></div>
      <div className="flight-levels" aria-label="Прогресс по уровням">{r.levelThresholds.map((threshold, i) => <div key={i} data-testid="flight-level" className={i < r.currentLevel ? 'passed' : ''} aria-label={`Уровень ${i + 1}: ${i < r.currentLevel ? 'пройден' : 'впереди'}`}><span>{String(i + 1).padStart(2, '0')}</span><i /><small>{multiplier(threshold)}</small>{r.boosterActivated && r.boosterLevel === i + 1 && <b>×{r.boosterMultiplier}</b>}</div>)}</div>
      <div className="level-toast" key={notice} role="status">{notice || 'Первый уровень откроет cashout'}</div>
    </div>
    <div className="flight-dashboard"><div className="flight-stats"><div><span>Ставка</span><strong>{number(r.betAmount)}</strong></div><div><span>Бустер</span><strong>{r.boosterMultiplier === 1 ? 'Нет' : `×${r.boosterMultiplier}`} {r.boosterMultiplier > 1 && <small>{r.boosterActivated ? 'активен' : r.cashoutPerformed ? 'не сработает' : 'скрыт'}</small>}</strong></div><div><span>Игровые очки</span><strong data-testid="round-score">{number(r.roundScore)} ✧</strong></div></div>
      {r.cashoutPerformed ? <div className="cashout-fixed" role="status"><strong>Зафиксировано {number(r.winAmount)} бонусов · {multiplier(r.cashoutMultiplier!)}</strong><span>Могли бы забрать больше</span><small>Выплата сохранена. Шар продолжает полёт до падения.</small></div> : <div className="cashout-action"><button className="primary" onClick={onCashout} disabled={!r.cashoutAvailable || busy || crashed || connection !== 'connected'}>{crashed ? 'Полёт завершён' : busy ? 'Фиксируем…' : 'Забрать'} <span aria-hidden="true">↙</span></button><small>{crashed ? 'Готовим результат…' : r.cashoutAvailable ? 'Зафиксировать текущий коэффициент' : 'Доступно после первого уровня'}</small></div>}
    </div><button className="fairness-link" onClick={onFairness}>◇ Проверить честность</button>
  </section>
}
