import { useCallback, useEffect, useMemo, useState, useSyncExternalStore, type CSSProperties } from 'react'
import type { Api, Catalog, Preset, Theme, User, Wallet } from '../api/types'
import { number } from '../game/format'
import { GameSession, message } from '../game/session'
import { Brand } from './App'
import { Setup, Flight } from './Gameplay'
import { FairnessDialog, History, Modal, ResultScreen, TournamentPanel } from './Panels'

export function GameHome({ user, api, onLogout }: { user: User; api: Api; onLogout: () => Promise<void> }) {
  const roundKey = `air-balloon-active-${api.mode}-${user.id}`
  const [theme, setTheme] = useState<Theme>(() => localStorage.getItem('air-balloon-theme') === 'RED' ? 'RED' : 'GREEN')
  const [stake, setStake] = useState(100); const [booster, setBooster] = useState(1)
  const [wallet, setWallet] = useState<Wallet | null>(null); const [catalog, setCatalog] = useState<Catalog | null>(null)
  const [page, setPage] = useState<'game' | 'history' | 'tournament'>('game'); const [rules, setRules] = useState(false); const [fairness, setFairness] = useState(false)
  const [error, setError] = useState(''); const [preset, setPreset] = useState<Preset>('WIN')
  const [resourceAttempt, setResourceAttempt] = useState(0)
  const [resultRoundId, setResultRoundId] = useState<string | null>(null)
  const session = useMemo(() => new GameSession(api.game, id => { if (id) localStorage.setItem(roundKey, id); else localStorage.removeItem(roundKey) }), [api, roundKey])
  const state = useSyncExternalStore(session.subscribe, session.getSnapshot)
  const r = state.round
  const refreshWallet = useCallback(() => api.economy.getBalance().then(setWallet).catch(e => setError(message(e))), [api])
  useEffect(() => { let live = true; api.catalog.get().then(c => { if (live) { setCatalog(c); setStake(value => value >= c.stakeRules.minimum && value <= c.stakeRules.maximum ? value : c.stakes[0]); setBooster(value => c.boosters.includes(value) ? value : c.boosters[0]) } }).catch(e => { if (live) setError(message(e)) }); return () => { live = false } }, [api, resourceAttempt])
  useEffect(() => { void refreshWallet() }, [refreshWallet, resourceAttempt, r?.id, r?.cashoutPerformed, r?.roundScore, r?.status])
  useEffect(() => { session.activate(); const saved = localStorage.getItem(roundKey); if (saved) void session.recover(saved); return session.dispose }, [session, roundKey])
  useEffect(() => { if (r?.status !== 'FINISHED') return; const timer = setTimeout(() => setResultRoundId(r.id), 1300); return () => clearTimeout(timer) }, [r?.id, r?.status])
  const selectTheme = (t: Theme) => { setTheme(t); localStorage.setItem('air-balloon-theme', t) }
  const active = !!r && r.status !== 'FINISHED'
  return <div className={`app theme-${(r?.theme ?? theme).toLowerCase()}`}>
    <header className="topbar"><Brand /><nav aria-label="Основная навигация"><button aria-current={page === 'game' ? 'page' : undefined} onClick={() => setPage('game')}>Игра</button><button aria-current={page === 'history' ? 'page' : undefined} onClick={() => setPage('history')}>История</button><button aria-current={page === 'tournament' ? 'page' : undefined} onClick={() => setPage('tournament')}>Турнир</button><button onClick={() => setRules(true)}>Правила</button></nav><span className="mode-badge">{api.mode === 'mock' ? '● ДЕМО' : '● REAL API'}</span></header>
    <main className="layout"><section className="main-content"><div className="section-heading"><div><p className="eyebrow">ВАШ МАЛЕНЬКИЙ ПОБЕГ В НЕБО</p><h1>{page === 'history' ? 'История полётов' : page === 'tournament' ? 'Турнир пилотов' : r ? 'Ловите свой момент' : 'Куда полетим сегодня?'}</h1></div><span className="edition">01 / BALLOON</span></div>
      {(error || state.error) && <div role="alert" className="error error-box">{error || state.error} <button className="text-button" onClick={() => { setError(''); session.clearError(); setResourceAttempt(n => n + 1); const saved = r?.id ?? localStorage.getItem(roundKey); if (saved) void session.recover(saved) }}>Повторить чтение</button></div>}
      {page === 'history' ? <History api={api} onBack={() => setPage('game')} /> : page === 'tournament' ? <TournamentPanel api={api} onBack={() => setPage('game')} /> : r ? <>{resultRoundId === r.id ? <ResultScreen api={api} round={r} onAgain={() => { selectTheme(r.theme); session.again() }} onHistory={() => setPage('history')} onFairness={() => setFairness(true)} /> : <Flight round={r} connection={state.connection} busy={state.busy} notice={state.notice} onCashout={session.cashout} onFairness={() => setFairness(true)} onReconnect={() => void session.recover()} />}</> : catalog && wallet ? <Setup theme={theme} onTheme={selectTheme} catalog={catalog} stake={stake} onStake={setStake} booster={booster} onBooster={setBooster} balance={wallet.bonusBalance} busy={state.busy || state.connection === 'recovering'} onStart={() => void session.start({ theme, betAmount: stake, boosterMultiplier: booster })} onRules={() => setRules(true)} onHistory={() => setPage('history')} /> : <div className="loading" role="status">Загружаем варианты полёта…</div>}
      {api.dev && <details className="dev-panel"><summary>Демо-лаборатория <span>сценарии и связь</span></summary><div className="dev-controls"><label>Сценарий<select value={preset} disabled={active} onChange={e => { const p = e.target.value as Preset; setPreset(p); api.dev!.setPreset(p) }}><option>WIN</option><option>LOSE</option><option>BOOSTER</option><option>RECONNECT</option></select></label><button className="secondary" disabled={!active || state.connection !== 'connected'} onClick={() => api.dev!.disconnect()}>Simulate disconnect</button><button className="secondary" disabled={active} onClick={() => { api.dev!.setBalance(user.id, 50); void refreshWallet() }}>Баланс: 50</button><button className="secondary" disabled={active} onClick={() => { api.dev!.setBalance(user.id, 5000); void refreshWallet() }}>Баланс: 5 000</button></div><p>Только MOCK. WIN — 18 сек. для cashout; LOSE — падение на 8-й сек.; BOOSTER — 22 сек., бустер на скрытом уровне; RECONNECT — 18 сек. для проверки отключения. Нажатие «Забрать» всегда остаётся за вами.</p>{state.recovered > 0 && <p role="status">Состояние восстановлено из snapshot/replay · {state.recovered}</p>}</details>}
      <footer className="game-footer"><span>Меньше суеты. Больше неба.</span><span>{api.mode === 'mock' ? 'Симуляция · не реальные выплаты' : 'Состояние определяет сервер'}</span></footer>
    </section><aside className="profile-panel" aria-label="Профиль пользователя"><div className="profile-top"><span className="eyebrow">ВАШ ПРОФИЛЬ</span><button className="text-button" disabled={active} title={active ? 'Дождитесь завершения раунда' : undefined} onClick={() => void onLogout().catch(e => setError(message(e)))}>Выйти</button></div><div className="profile-photo" style={{ '--profile-color': user.color } as CSSProperties} aria-label="Заглушка фотографии профиля">{user.initials}</div><h2>{user.name}</h2><p className="username">@{user.login}</p><div className="wallet"><span>Бонусный баланс</span><strong data-testid="balance">{wallet ? number(wallet.bonusBalance) : '—'}</strong><small>бонусов для новых полётов</small></div><div className="score-wallet"><span>Игровые очки</span><strong>{wallet ? number(wallet.gameScore) : '—'} <span aria-hidden="true">✧</span></strong><small>Отдельный счёт, не бонусы</small></div><div className="profile-tip"><span aria-hidden="true">↗</span><p>Лучший момент —<br />тот, который вы поймали.</p></div><div className="profile-note"><i />{api.mode === 'mock' ? 'Тестовый профиль · локальный прогресс' : 'Серверный профиль'}</div></aside></main>
    {rules && <Modal title="Как устроен полёт" onClose={() => setRules(false)}><ol className="rules"><li><strong>Выберите маршрут.</strong> GREEN — {catalog?.levels.GREEN ?? 9} уровней, RED — {catalog?.levels.RED ?? 12}. Больше уровней — более длинная шкала полёта, не гарантия выигрыша.</li><li><strong>Сделайте ставку.</strong> Списывается выбранная сумма: {number(stake)} бонусов.</li><li><strong>Поднимайтесь выше.</strong> Коэффициент растёт. «Забрать» доступно после первого уровня.</li><li><strong>Поймайте бустер.</strong> Усиление сработает на скрытом сервером уровне, если вы ещё не забрали выигрыш.</li><li><strong>Заберите вовремя.</strong> Выплата и коэффициент фиксируются. Шар летит до падения; повторно забрать нельзя.</li><li><strong>Учитывайте риск.</strong> Без cashout при падении ставка теряется. Успешный cashout сохраняется после crash.</li><li><strong>Собирайте очки.</strong> Итоговые очки, бонусы и награды определяет сервер.</li></ol><p className="muted">{api.mode === 'mock' ? 'Демо показывает механику интерфейса на локальных данных.' : 'Каталог, экономика и результаты приходят из PostgreSQL через игровой сервер.'}</p></Modal>}
    {fairness && r && <FairnessDialog api={api} round={r} onClose={() => setFairness(false)} />}
  </div>
}
