game:
  random-mode: NORMAL
  config:
    min-crash-multiplier: 1.00
    max-crash-multiplier: 30.00
    alpha: 0.03
    green:
      booster-weights: [0, 0, 1, 0, 0, 0, 0, 0, 0]
    red:
      booster-weights: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
app:
  allow-fixed-seed: true
