package ru.airballoon.game.domain;

public enum GameError {
    ROUND_NOT_FOUND, ROUND_NOT_RUNNING, CASHOUT_NOT_AVAILABLE_YET,
    ALREADY_CASHED_OUT, ROUND_ALREADY_CRASHED, INVALID_BOOSTER, INVALID_THEME,
    INVALID_BET, INVALID_GAME_CONFIG, FORBIDDEN_ROUND_ACCESS, AUTH_REQUIRED, UNAUTHENTICATED,
    INSUFFICIENT_BALANCE, INVALID_REQUEST, INTEGRATION_UNAVAILABLE
}
